### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [januszbak34/python#1]
1. Wyeliminować zmienne globalne (2. rozdział Poradnika).
2. Stałe nazywać dużymi literami (2. rozdział).
3. Luźny kod powkładać do `main()` (3. rozdział).
4. `kod` nie trzymać jako magiczne liczby, tylko jako znaki.
5. Dopisać jakieś testy.

**Comment by SlawomirK77** [comment]
Poprawione.
Czy nazwy zmiennych i kod są wystarczajace, czy powinienem dodać jakieś docstringi?

**Comment by SlawomirK77** [comment]
Naniosłem poprawki na kod i dopisałem testy, o których Pan wspomniał (`czy_wygrana()`, `policz_bomby()`).

**Comment by MarcinCiura** [comment]
Dziękuję za poprawki. LGTM. Gratuluję, jest Pan trzydziesty pierwszy,
